import React, { useState } from 'react';
import { Activity, ArrowDownLeft, ArrowLeftRight, ArrowUpRight, Bell, Boxes, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, ClipboardList, Command, Download, FileClock, LayoutDashboard, Menu, MoreHorizontal, Package, Plus, Search, Settings2, ShieldCheck, Truck, Users, X } from 'lucide-react';

const bases = ['All bases', 'Fort Liberty', 'Camp Pendleton', 'Joint Base Lewis-McChord', 'Fort Cavazos'];
const assets = [
  {name:'M4A1 Carbine',code:'WPN-001',type:'Weapons',opening:1240,purchase:120,in:48,out:32,assigned:846,expended:0,status:'Operational',icon:'▰'},
  {name:'JLTV (M1280)',code:'VEH-014',type:'Vehicles',opening:86,purchase:8,in:2,out:5,assigned:62,expended:0,status:'Operational',icon:'▱'},
  {name:'5.56mm Ball M855',code:'AMM-056',type:'Ammunition',opening:48500,purchase:12000,in:4200,out:2800,assigned:9200,expended:1830,status:'Low stock',icon:'◉'},
  {name:'M2 Browning .50 Cal',code:'WPN-024',type:'Weapons',opening:148,purchase:12,in:6,out:3,assigned:112,expended:0,status:'Operational',icon:'▰'},
  {name:'HMMWV M1151',code:'VEH-009',type:'Vehicles',opening:214,purchase:14,in:4,out:7,assigned:168,expended:0,status:'Operational',icon:'▱'},
];
const transactions = [
  {kind:'Transfer in',asset:'M4A1 Carbine',detail:'From Camp Pendleton · TRF-2408',qty:'+24',date:'Today, 09:42',state:'Completed',icon:'in'},
  {kind:'Purchase',asset:'5.56mm Ball M855',detail:'PO-2024-184 · Contract delivery',qty:'+4,000',date:'Today, 08:15',state:'Received',icon:'purchase'},
  {kind:'Assignment',asset:'JLTV (M1280)',detail:'Assigned to 2nd Battalion, 82nd ABN',qty:'−6',date:'Yesterday, 16:30',state:'Completed',icon:'assign'},
  {kind:'Transfer out',asset:'M2 Browning .50 Cal',detail:'To Fort Cavazos · TRF-2406',qty:'−3',date:'Yesterday, 14:12',state:'In transit',icon:'out'},
  {kind:'Expenditure',asset:'5.56mm Ball M855',detail:'Training exercise · EX-118',qty:'−1,830',date:'Sep 22, 11:06',state:'Recorded',icon:'expended'},
];
const nav = [{title:'OVERVIEW',items:[['Dashboard',LayoutDashboard],['Asset inventory',Boxes],['Movement log',ArrowLeftRight]]},{title:'OPERATIONS',items:[['Purchases',Package],['Transfers',Truck],['Assignments & use',ClipboardList]]},{title:'ADMINISTRATION',items:[['Personnel & roles',Users],['Audit trail',FileClock]]}];
function App(){
  const [page,setPage]=useState('Dashboard'),[range,setRange]=useState('Last 30 days'),[base,setBase]=useState('All bases'),[type,setType]=useState('All equipment'),[query,setQuery]=useState(''),[role,setRole]=useState('Administrator'),[showNet,setShowNet]=useState(false),[modal,setModal]=useState(''),[mobile,setMobile]=useState(false),[toast,setToast]=useState('');
  const visibleAssets=assets.filter(a=>(type==='All equipment'||a.type===type)&&(!query||`${a.name} ${a.code}`.toLowerCase().includes(query.toLowerCase())));
  const notify=(s)=>{setToast(s);setTimeout(()=>setToast(''),2800)};
  const title=page==='Dashboard'?'Command overview':page;
  return <div className="app-shell">
    <aside className={`sidebar ${mobile?'open':''}`}>
      <div className="brand"><div className="brand-mark"><Command size={19}/></div><div><strong>SENTINEL</strong><span>ASSET COMMAND</span></div><button className="mobile-close" onClick={()=>setMobile(false)}><X size={18}/></button></div>
      <div className="unit-card"><div className="unit-seal">82</div><div><strong>82nd Airborne Division</strong><span>Fort Liberty, NC</span></div><ChevronDown size={15}/></div>
      <nav>{nav.map(group=><section className="nav-group" key={group.title}><small>{group.title}</small>{group.items.map(([name,Icon])=><button key={name} className={`nav-item ${page===name?'active':''}`} onClick={()=>{setPage(name);setMobile(false)}}><Icon size={17}/><span>{name}</span>{name==='Transfers'&&<i className="nav-count">3</i>}</button>)}</section>)}</nav>
      <div className="sidebar-bottom"><div className="readiness"><div className="ready-icon"><ShieldCheck size={17}/></div><div><strong>System readiness</strong><span><i/> All systems operational</span></div></div><button className="nav-item settings" onClick={()=>notify('Settings are up to date')}><Settings2 size={17}/><span>Settings</span></button><div className="profile"><div className="avatar">JD</div><div><strong>Jordan Davis</strong><span>Division Logistics</span></div><MoreHorizontal size={18}/></div></div>
    </aside>
    {mobile&&<button className="scrim" onClick={()=>setMobile(false)} aria-label="Close navigation"/>}
    <main className="main-area">
      <header className="topbar"><button className="mobile-menu" onClick={()=>setMobile(true)}><Menu size={19}/></button><div className="crumb">Operations <span>/</span> <b>{page}</b></div><div className="top-actions"><div className="secure-pill"><span/> SECURE SESSION</div><button className="icon-button" onClick={()=>notify('You are all caught up')}><Bell size={18}/><i/></button><div className="top-divider"/><label className="role-switch"><span>VIEW AS</span><select value={role} onChange={e=>setRole(e.target.value)}><option>Administrator</option><option>Base Commander</option><option>Logistics Officer</option></select><ChevronDown size={13}/></label></div></header>
      <div className="content"><div className="page-heading"><div><div className="eyebrow"><span className="live-dot"/> LOGISTICS COMMAND <span className="eyebrow-sep">/</span> FY 2024</div><h1>{title}<span className="heading-period">.</span></h1><p>Monitor readiness, movement, and accountability across your area of responsibility.</p></div><div className="heading-actions"><button className="button secondary" onClick={()=>notify('Report prepared for download')}><Download size={15}/> Export report</button><button className="button primary" onClick={()=>setModal('Record transaction')}><Plus size={16}/> Record transaction</button></div></div>
        <div className="filter-bar"><div className="filter-label"><Settings2 size={14}/> FILTERS</div><div className="filter-select"><span>PERIOD</span><select value={range} onChange={e=>setRange(e.target.value)}><option>Last 30 days</option><option>Last 7 days</option><option>This quarter</option><option>Year to date</option></select><ChevronDown size={13}/></div><div className="filter-select"><span>BASE</span><select value={base} onChange={e=>setBase(e.target.value)}>{bases.map(b=><option key={b}>{b}</option>)}</select><ChevronDown size={13}/></div><div className="filter-select equipment-filter"><span>EQUIPMENT TYPE</span><select value={type} onChange={e=>setType(e.target.value)}><option>All equipment</option><option>Weapons</option><option>Vehicles</option><option>Ammunition</option></select><ChevronDown size={13}/></div><button className="clear-filter" onClick={()=>{setRange('Last 30 days');setBase('All bases');setType('All equipment')}}>Clear filters</button><div className="filter-date">SEP 01 — SEP 30, 2024 <ChevronDown size={13}/></div></div>
        {page==='Dashboard'?<><div className="section-title"><h2>Readiness snapshot</h2><span>Updated just now <i className="refresh-dot"/></span></div>
        <div className="metric-grid">
          <Metric title="OPENING BALANCE" value="50,188" note="Assets at period start" Icon={Boxes} accent="sage" trend="BASELINE"/>
          <div className={`metric-card movement ${showNet?'selected':''}`} role="button" tabIndex="0" onClick={()=>setShowNet(true)}><div className="metric-top"><span>NET MOVEMENT</span><span className="metric-icon mint"><Activity size={17}/></span></div><div className="metric-value positive">+15,261</div><div className="metric-bottom"><span className="trend-positive"><ArrowUpRight size={14}/> 12.8%</span><span>vs. previous period</span><button className="details-link" onClick={(e)=>{e.stopPropagation();setShowNet(true)}}>VIEW DETAILS <ChevronRight size={12}/></button></div></div>
          <Metric title="CLOSING BALANCE" value="65,449" note="Current available inventory" Icon={Package} accent="blue" trend="AS OF SEP 30"/>
          <Metric title="ASSIGNED" value="10,388" note="Issued to units & personnel" Icon={Users} accent="sand" trend="20.7% OF TOTAL"/>
          <Metric title="EXPENDED" value="1,830" note="Recorded consumption" Icon={ArrowUpRight} accent="rose" trend="THIS PERIOD"/>
        </div>
        <div className="dashboard-grid"><section className="panel inventory-panel"><div className="panel-header"><div><h2>Inventory by equipment</h2><p>Balance and status across tracked assets</p></div><button className="text-action" onClick={()=>setPage('Asset inventory')}>VIEW INVENTORY <ChevronRight size={13}/></button></div><div className="table-tools"><div className="search-box"><Search size={15}/><input placeholder="Search equipment..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><button className="table-filter" onClick={()=>setType(type==='All equipment'?'Weapons':'All equipment')}><Settings2 size={15}/> Filter</button></div><div className="table-scroll"><table><thead><tr><th>EQUIPMENT</th><th>OPENING</th><th>IN</th><th>OUT</th><th>CLOSING</th><th>ASSIGNED</th><th>STATUS</th></tr></thead><tbody>{visibleAssets.slice(0,5).map(a=>{const closing=a.opening+a.purchase+a.in-a.out;return <tr key={a.code}><td><div className="asset-cell"><span className={`asset-symbol ${a.type.toLowerCase()}`}>{a.icon}</span><div><strong>{a.name}</strong><span>{a.code} <i>·</i> {a.type}</span></div></div></td><td>{a.opening.toLocaleString()}</td><td className="number-in">+{a.in.toLocaleString()}</td><td className="number-out">−{a.out.toLocaleString()}</td><td className="closing-number">{closing.toLocaleString()}</td><td>{a.assigned.toLocaleString()}</td><td><span className={`status ${a.status==='Low stock'?'low':''}`}><i/>{a.status}</span></td></tr>})}</tbody></table></div><div className="table-footer">SHOWING <b>{visibleAssets.length} OF 24</b> EQUIPMENT TYPES <button onClick={()=>setPage('Asset inventory')}>View all inventory <ChevronRight size={13}/></button></div></section>
          <section className="panel activity-panel"><div className="panel-header"><div><h2>Recent movements</h2><p>Latest inventory transactions</p></div><button className="icon-button more-button" onClick={()=>setPage('Movement log')}><MoreHorizontal size={19}/></button></div><div className="activity-list">{transactions.map((t,i)=><div className="activity-row" key={i}><div className={`activity-icon ${t.icon}`}>{t.icon==='in'?<ArrowDownLeft size={15}/>:t.icon==='out'?<ArrowUpRight size={15}/>:t.icon==='purchase'?<Package size={15}/>:t.icon==='assign'?<Users size={15}/>:<Activity size={15}/>}</div><div className="activity-info"><strong>{t.kind}<span> · </span>{t.asset}</strong><span>{t.detail}</span><small>{t.date}</small></div><div className="activity-end"><b className={t.qty.startsWith('+')?'qty-plus':''}>{t.qty}</b><span>{t.state}</span></div></div>)}</div><button className="activity-footer" onClick={()=>setPage('Movement log')}>VIEW ALL MOVEMENTS <ChevronRight size={13}/></button></section></div>
        <div className="bottom-strip"><div><div className="strip-icon"><ShieldCheck size={17}/></div><span><strong>Full accountability. Every movement.</strong><small>Every transaction is time-stamped and recorded in the audit trail.</small></span></div><button onClick={()=>setPage('Audit trail')}>OPEN AUDIT TRAIL <ChevronRight size={13}/></button><div className="pager"><button><ChevronLeft size={14}/></button><span>01 <i>/</i> 04</span><button><ChevronRight size={14}/></button></div></div>
        </>:<OperationsPage page={page} query={query} setQuery={setQuery} setModal={setModal} notify={notify} />}
        <footer>UNCLASSIFIED <span>•</span> SENTINEL LOGISTICS MANAGEMENT <span className="footer-right">DATA REFRESHED 30 SEP 2024, 14:32Z <CircleHelp size={13}/></span></footer>
      </div>
    </main>
    {showNet&&<div className="modal-backdrop" onClick={()=>setShowNet(false)}><div className="modal net-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">MOVEMENT BREAKDOWN</span><h2>Net movement <span className="positive">+15,261</span></h2><p>Purchases and transfers in, less transfers out · Sep 01–30</p></div><button className="icon-button" onClick={()=>setShowNet(false)}><X size={17}/></button></div><div className="movement-breakdown">{[['Purchases','+12,154','purchase'],['Transfers in','+5,382','in'],['Transfers out','−2,275','out']].map(([k,v,c])=><div key={k}><span className={`breakdown-icon ${c}`}>{c==='purchase'?<Package size={16}/>:c==='in'?<ArrowDownLeft size={16}/>:<ArrowUpRight size={16}/>}</span><span>{k}<small>{c==='purchase'?'34 purchase orders':c==='in'?'18 incoming transfers':'12 outgoing transfers'}</small></span><b className={c==='out'?'negative':'positive'}>{v}</b></div>)}</div><div className="net-total"><span>NET MOVEMENT</span><b>+15,261 <small>assets</small></b></div><button className="button primary modal-action" onClick={()=>{setShowNet(false);setPage('Movement log')}}>Open movement log <ChevronRight size={15}/></button></div></div>}
    {modal&&<div className="modal-backdrop" onClick={()=>setModal('')}><div className="modal transaction-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">INVENTORY CONTROL</span><h2>Record transaction</h2><p>Add a movement to the auditable asset ledger.</p></div><button className="icon-button" onClick={()=>setModal('')}><X size={17}/></button></div><div className="form-grid"><label>TRANSACTION TYPE<select><option>Purchase received</option><option>Transfer between bases</option><option>Assignment</option><option>Expenditure</option></select></label><label>EQUIPMENT<select>{assets.map(a=><option key={a.code}>{a.name}</option>)}</select></label><label>QUANTITY<input type="number" placeholder="Enter quantity"/></label><label>TRANSACTION DATE<input type="date" defaultValue="2024-09-30"/></label><label className="wide-label">NOTES<input placeholder="Order reference, receiving unit, or purpose"/></label></div><div className="form-actions"><button className="button secondary" onClick={()=>setModal('')}>Cancel</button><button className="button primary" onClick={()=>{setModal('');notify('Transaction saved to the audit trail')}}><Plus size={15}/> Save transaction</button></div></div></div>}
    {toast&&<div className="toast"><ShieldCheck size={16}/>{toast}</div>}
  </div>
}
function Metric({title,value,note,Icon,accent,trend}){return <div className="metric-card"><div className="metric-top"><span>{title}</span><span className={`metric-icon ${accent}`}><Icon size={17}/></span></div><div className="metric-value">{value}</div><div className="metric-bottom"><span>{note}</span><small>{trend}</small></div></div>}
function OperationsPage({page,query,setQuery,setModal,notify}){
 const purchase=page==='Purchases', transfer=page==='Transfers', assignment=page==='Assignments & use';
 const title=page==='Asset inventory'?'Equipment inventory':page==='Movement log'?'Movement history':page==='Audit trail'?'Audit trail':page==='Personnel & roles'?'Personnel & access':page;
 let rows=purchase?transactions.filter(t=>t.kind==='Purchase'):transfer?transactions.filter(t=>t.kind.includes('Transfer')):assignment?transactions.filter(t=>['Assignment','Expenditure'].includes(t.kind)):transactions;
 rows=rows.filter(r=>!query||`${r.asset} ${r.kind} ${r.detail}`.toLowerCase().includes(query.toLowerCase()));
 const canCreate= !['Audit trail','Personnel & roles'].includes(page);
 return <section className="panel operations-panel"><div className="panel-header"><div><h2>{title}</h2><p>{purchase?'Procurement records by base, date, and equipment type.':transfer?'Track dispatches, receipts, and inter-base movement.':assignment?'Issued equipment and recorded consumption.':'Searchable, time-stamped logistics records.'}</p></div>{canCreate&&<button className="button primary" onClick={()=>setModal('Record transaction')}><Plus size={15}/> New record</button>}</div><div className="table-tools"><div className="search-box"><Search size={15}/><input placeholder={`Search ${title.toLowerCase()}...`} value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="table-filter" onClick={()=>notify('Filters are controlled from the bar above')}><Settings2 size={15}/> Filter</button></div><div className="table-scroll"><table className="operations-table"><thead><tr><th>TRANSACTION</th><th>EQUIPMENT</th><th>BASE / DETAILS</th><th>QUANTITY</th><th>DATE & TIME</th><th>STATUS</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><div className="asset-cell"><span className={`activity-icon ${r.icon}`}><Activity size={14}/></span><div><strong>{r.kind}</strong><span>LOG-{2408-i}</span></div></div></td><td>{r.asset}</td><td>{r.detail}</td><td className={r.qty.startsWith('+')?'number-in':'number-out'}>{r.qty}</td><td>{r.date}</td><td><span className="status"><i/>{r.state}</span></td></tr>)}</tbody></table></div><div className="table-footer">SHOWING <b>{rows.length} RECORDS</b><button onClick={()=>notify('All available records are shown')}>Showing latest records</button></div></section>
}
export default App;
